# site settings
title: Mark Dyehouse
subtitle: Roboticist and Software Engineer
email: mdyehous@alumni.cmu.edu
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "ThePenultimatum.github.io" # the base hostname & protocol for your site
author: Mark Dyehouse
street_address:
city: New Haven
state: Connecticut
zip_code:
country: USA
phone: S1x on3 six, three z3r0 e1ght, f0ur five f1ve 53ven

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 20

# social settings

github_url: https://github.com/ThePenultimatum/
linkedin_url: https://www.linkedin.com/in/mark-dyehouse-71a66880/

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag